// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title VerificationRegistry
 * @notice Stores cryptographically verified KYC status on-chain
 * @dev This is a simplified version that uses admin signatures instead of full KRNL integration
 *
 * Architecture:
 * - Admin wallet signs verification messages off-chain
 * - Contract verifies signature and stores verification status
 * - CampaignManager checks this contract before allowing campaign creation
 *
 * Security Features:
 * - Signature-based authorization (only admin can verify)
 * - Nonce-based replay protection
 * - Event logging for transparency
 * - Revocation capability for compliance
 */
contract VerificationRegistry {
    // Admin address authorized to verify creators
    address public admin;

    // Mapping: creator address => verification status
    mapping(address => bool) public isVerified;

    // Mapping: creator address => verification timestamp
    mapping(address => uint256) public verifiedAt;

    // Mapping: creator address => verification provider (e.g., "sumsub")
    mapping(address => string) public verificationProvider;

    // Mapping: creator address => nonce (for replay protection)
    mapping(address => uint256) public nonces;

    // Events
    event CreatorVerified(
        address indexed creator,
        string provider,
        uint256 timestamp
    );

    event VerificationRevoked(address indexed creator, uint256 timestamp);

    event AdminUpdated(address indexed oldAdmin, address indexed newAdmin);

    /**
     * @notice Constructor sets the admin address
     * @param _admin The address authorized to verify creators
     */
    constructor(address _admin) {
        require(_admin != address(0), "Invalid admin address");
        admin = _admin;
        emit AdminUpdated(address(0), _admin);
    }

    /**
     * @notice Verify a creator with admin signature
     * @param creator The address to verify
     * @param provider The verification provider (e.g., "sumsub")
     * @param nonce The nonce for replay protection
     * @param signature The admin's signature
     *
     * @dev The signature must be generated by signing:
     *      keccak256(abi.encodePacked(creator, provider, nonce))
     */
    function verifyCreator(
        address creator,
        string calldata provider,
        uint256 nonce,
        bytes calldata signature
    ) external {
        require(!isVerified[creator], "Already verified");
        require(nonce == nonces[creator], "Invalid nonce");

        // Verify signature
        bytes32 messageHash = keccak256(
            abi.encodePacked(creator, provider, nonce)
        );
        bytes32 ethSignedMessageHash = getEthSignedMessageHash(messageHash);

        require(
            recoverSigner(ethSignedMessageHash, signature) == admin,
            "Invalid signature"
        );

        // Store verification
        isVerified[creator] = true;
        verifiedAt[creator] = block.timestamp;
        verificationProvider[creator] = provider;
        nonces[creator]++;

        emit CreatorVerified(creator, provider, block.timestamp);
    }

    /**
     * @notice Revoke verification (admin only)
     * @param creator The address to revoke
     * @param nonce The nonce for replay protection
     * @param signature The admin's signature
     */
    function revokeVerification(
        address creator,
        uint256 nonce,
        bytes calldata signature
    ) external {
        require(isVerified[creator], "Not verified");
        require(nonce == nonces[creator], "Invalid nonce");

        // Verify signature
        bytes32 messageHash = keccak256(
            abi.encodePacked(creator, "revoke", nonce)
        );
        bytes32 ethSignedMessageHash = getEthSignedMessageHash(messageHash);

        require(
            recoverSigner(ethSignedMessageHash, signature) == admin,
            "Invalid signature"
        );

        // Revoke verification
        isVerified[creator] = false;
        nonces[creator]++;

        emit VerificationRevoked(creator, block.timestamp);
    }

    /**
     * @notice Update admin address (current admin only)
     * @param newAdmin The new admin address
     * @param nonce The nonce for replay protection
     * @param signature The current admin's signature
     */
    function updateAdmin(
        address newAdmin,
        uint256 nonce,
        bytes calldata signature
    ) external {
        require(newAdmin != address(0), "Invalid admin address");
        require(nonce == nonces[admin], "Invalid nonce");

        // Verify signature
        bytes32 messageHash = keccak256(
            abi.encodePacked(newAdmin, "admin", nonce)
        );
        bytes32 ethSignedMessageHash = getEthSignedMessageHash(messageHash);

        require(
            recoverSigner(ethSignedMessageHash, signature) == admin,
            "Invalid signature"
        );

        address oldAdmin = admin;
        admin = newAdmin;
        nonces[oldAdmin]++;

        emit AdminUpdated(oldAdmin, newAdmin);
    }

    /**
     * @notice Get the Ethereum Signed Message hash
     * @param messageHash The original message hash
     * @return bytes32 The Ethereum signed message hash
     */
    function getEthSignedMessageHash(
        bytes32 messageHash
    ) internal pure returns (bytes32) {
        return
            keccak256(
                abi.encodePacked(
                    "\x19Ethereum Signed Message:\n32",
                    messageHash
                )
            );
    }

    /**
     * @notice Recover the signer address from a signature
     * @param ethSignedMessageHash The Ethereum signed message hash
     * @param signature The signature
     * @return address The signer address
     */
    function recoverSigner(
        bytes32 ethSignedMessageHash,
        bytes memory signature
    ) internal pure returns (address) {
        require(signature.length == 65, "Invalid signature length");

        bytes32 r;
        bytes32 s;
        uint8 v;

        assembly {
            r := mload(add(signature, 32))
            s := mload(add(signature, 64))
            v := byte(0, mload(add(signature, 96)))
        }

        return ecrecover(ethSignedMessageHash, v, r, s);
    }
}
